local repo = 'https://raw.githubusercontent.com/KingScriptAE/No-sirve-nada./refs/heads/main/'
local Library = loadstring(game:HttpGet(repo .. 'Library.lua'))()
local ThemeManager = loadstring(game:HttpGet(repo .. 'addons/ThemeManager.lua'))()
local SaveManager = loadstring(game:HttpGet(repo .. 'addons/SaveManager.lua'))()

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local localPlayer = Players.LocalPlayer
local playerGui = localPlayer:WaitForChild("PlayerGui")

-- ======================【全局变量 明文保留】======================
getgenv().NWKZ_AutoCast = false
getgenv().NWKZ_Anchor = false
local autoCastThread = nil
local fishingBarLockConnection = nil

local StageConfig = {
    Phase1 = {
        CenterTolerance = 0.042,
        PulseInterval = 0.045
    },
    Phase2 = {
        CenterTolerance = 0.048,
        PulseInterval = 0.038
    }
}

local config = {
    AutoBossRhythm = false,
    CenterTolerance = StageConfig.Phase1.CenterTolerance,
    PulseInterval = StageConfig.Phase1.PulseInterval
}
local runThread = nil
local lastClickTime = 0
local wasOnCenter = false
-- =================================================================


local obfuscatedLogic = [[
--[[==== 待混淆片段开始 ====]]
--luast:ignore
-- generated by luast v1.0.1 https://luast.clv.cloud
local ba; local aL; local aJ; local aM; local aK; local aI; ba = { 871, function() local a_, a0, a1, a2, a3 = nil, nil, nil, nil, nil; local a4 = nil; a4 = 1; while true do a4 = 2181. - a4; do if a4 < 2180 then if a4 < 2174 then if a4 < 2171 then break elseif a4 < 2172. then
if a4 == 2171 then local bc = ba; a0 = a_:FindFirstChild(bc[54.]); a1 = a_:FindFirstChild(bc[53]); a2 = not a1; a3 = not a0; a4 = if a3 then 3. else 5 else a4 = 2174; continue end elseif a4 < 2173 then return nil elseif a4 == 2173 then return { [ba[6.]] = a0,
[ba[53]] = a1, [ba[79]] = a_ } else a4 = 13827.; continue end elseif a4 < 2177 then if a4 < 2175. then a0 = a_:FindFirstChild(ba[50]); a4 = if not a0 then 4 else 2 elseif a4 < 2176 then aI(); return nil else a3 = a2; a4 = 3. end elseif a4 < 2178. then return nil
elseif a4 < 2179 then if a4 == 2178. then a4 = if a3 then 9. else 8 else a4 = 2173; continue end elseif a4 == 2179 then a_ = a0:FindFirstChild(ba[42.]); a4 = if not a_ then 6. else 10 else a4 = 2171; continue end elseif a4 < 11359 then if a4 < 9319 then if a4 < 2181. then
if a4 == 2180 then a_ = playerGui:FindFirstChild(ba[32]); a4 = if not a_ then 0. else 7 else a4 = 2181.; continue end elseif a4 < 2233 then if a4 == 2181. then return nil else a4 = 2174; continue end else break end else break end else break end end end end,
15., 13, 12., "Cursor", workspace, task.wait, 7, "PlayerGui", "RenderStepped", "BarFrame", "Bar", function() local a5, a6, a7, a8 = nil, nil, nil, nil; local a9 = nil; a9 = 15.; while true do a9 = 13822 - a9; do if a9 < 13815. then if a9 < 13811 then if a9 < 13809. then
if a9 < 13808 then if a9 < 4801 then break elseif a9 < 9343 then break elseif a9 < 13807 then break elseif a9 == 13807 then lastClickTime = ba[41]; wasOnCenter = false; a9 = 5 else a9 = 13808; continue end elseif a9 == 13808 then wasOnCenter = a7; local bd = ba[27.][ba[95]];
ba[37](ba[30.]); a9 = 4 else a9 = 9343; continue end elseif a9 < 13810 then if a9 == 13809. then a9 = 14 else a9 = 13811; continue end elseif a9 == 13810 then aL(); lastClickTime = a6; a9 = 13 else a9 = 13817; continue end elseif a9 < 13813 then if a9 < 13812. then
a9 = if config[ba[24.]] then 1 else 7 else wasOnCenter = false; local be = ba[27.][ba[95]]; ba[37](ba[30.]); a9 = 5 end elseif a9 < 13814 then if a9 == 13813 then a9 = if a6 - lastClickTime >= config[ba[94]] then 12. else 13 else a9 = 13809.; continue end else
a6 = os[ba[84.]](); a7 = aK(a5[ba[6.]], a5[ba[79]]); a8 = aK(a5[ba[53]], a5[ba[79]]); a5 = math.abs(a7 - a8); a7 = a5 < config[ba[100]]; a5 = a7; a9 = if a5 then 2 else 0. end elseif a9 < 13819 then if a9 < 13818. then if a9 < 13816 then if a9 == 13815. then
a9 = 6. else a9 = 13814; continue end elseif a9 < 13817 then if a9 == 13816 then a9 = 3. else a9 = 13820; continue end elseif a9 == 13817 then a9 = if true then 11 else 6. else a9 = 13819; continue end else a9 = 5 end elseif a9 < 13822 then if a9 < 13821. then
if a9 < 13820 then break elseif a9 == 13820 then a5 = not wasOnCenter; a9 = 0. else a9 = 13822; continue end elseif a9 == 13821. then a5 = aJ(); a9 = if not a5 then 10 else 8 else a9 = 4801; continue end elseif a9 < 15828. then if a9 == 13822 then a9 = if a5 then 9. else 14
else break end else break end end end end, "iv", 24., -1, 6., Game.GetService, "Visible", 11, "wait", "X", "AutoBossRhythm", Vector2.new, task.cancel, task, newproxy, 3686291680, 2, function() config[ba[100]] = StageConfig[ba[23]][ba[100]]; config[ba[94]] = StageConfig[ba[23]][ba[94]];
wasOnCenter = false end, 7, "__call", 9., Color3.fromRGB, 5, "clock", 608135816, 16, "liveLicense", 0., "BossFightBar", "\u{2705}BOSS\u{81EA}\u{52A8}\u{70B9}\u{51FB}\u{5F00}\u{542F}", UDim2, 4103061961, "1", 8, 3., 17, "Fishing", "spawn", task.spawn, "Hitbox",
function() local s = aM(); local bf = ba; mousemoveabs(s[bf[13]], s[bf[62]]); mouse1press(); local bg = bf[27.][bf[95]]; bf[37](); mouse1release() end, 4102276, UDim2.new, pcall, "FishingUI", 3843., 1, function(l, m) local bh = ba; local n = m[bh[98]][bh[13]];
local o = m[bh[96.]][bh[13]]; local p = l[bh[98]][bh[13]] + l[bh[96.]][bh[13]] / bh[22]; return math.clamp((p - n) / o, bh[41], bh[60.]) end, "Y", 608675615, 0.012, "ViewportSize", coroutine.close, 16777213, 3867., "CenterTolerance", "NWKZ_AutoCast", 2878,
"Pointer", "weight", "MainGui", 512, function() local bb = math.floor; local bi = ba; local j = bi[64][bi[52]][bi[85]]; return bi[49][bi[91]](bb(j[bi[13]] / bi[22]), bb(j[bi[62]] / bi[22])) end, "\u{274C}BOSS\u{81EA}\u{52A8}\u{70B9}\u{51FB}\u{5173}\u{95ED}",
"Position", "Container", "Events", "cancel", "Phase1", "GuiObject", "FishingBar", Vector2, 1024, "Scale", "CurrentCamera", "Progress", 4, "new", 402., 1091, "PulseInterval", 0.5, "AbsoluteSize", "Slider", "AbsolutePosition", workspace.CurrentCamera, 0.3, 1653856940 };
aI = nil; aJ = nil; aK = nil; aL = nil; aM = nil; local aN, aO, aP, aQ, aR, aS, aT, aU, aV, aX, aY, aZ = nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil; local aW = nil; aW = 0.; while true do aW = 15175 - aW; do if aW < 15155 then if aW < 15144. then
if aW < 15139 then if aW < 15136 then if aW < 15135. then if aW < 15134 then break else aN = ba[14]; aR = function(F) config.AutoBossRhythm = F; if runThread then task.cancel(runThread); runThread = nil end; if F then runThread = task.spawn(aN); Library:Notify("\u{2705}BOSS\u{81EA}\u{52A8}\u{70B9}\u{51FB}\u{5F00}\u{542F}", 2)
else Library:Notify("\u{274C}BOSS\u{81EA}\u{52A8}\u{70B9}\u{51FB}\u{5173}\u{95ED}", 2) end end; aO = function(I) if I then if not autoCastThread then autoCastThread = task.spawn(function() while true do if getgenv().NWKZ_AutoCast then pcall(function() local J = (ReplicatedStorage:FindFirstChild("Events"));
if J then J = ReplicatedStorage.Events:FindFirstChild("Fishing") end; if J then ReplicatedStorage.Events.Fishing:FireServer() elseif ReplicatedStorage:FindFirstChild("Fishing") then ReplicatedStorage.Fishing:FireServer() end end); task.wait(0.3) else break
end end; autoCastThread = nil end) end elseif autoCastThread then task.cancel(autoCastThread); autoCastThread = nil end end; aP = function(L) if L then if not fishingBarLockConnection then fishingBarLockConnection = RunService.RenderStepped:Connect(function()
pcall(function() local M = localPlayer:FindFirstChild("PlayerGui"); if not M then return end; local O = (M:FindFirstChild("MainGui")); if O then O = M.MainGui:FindFirstChild("Fishing") end; local N = O; if N then else N = M:FindFirstChild("Fishing") end; if N then else
N = M:FindFirstChild("FishingUI") end; local P = N; local Q = P; if Q then Q = P.Visible end; if not Q then return end; local R = (P:FindFirstChild("FishingBar")); if R then else R = P:FindFirstChild("BarFrame") end; if R then else R = P:FindFirstChild("Bar")
end; local S = R; if not S then return end; local T = (S:FindFirstChild("Bar")); if T then else T = S:FindFirstChild("Slider") end; if T then else T = S:FindFirstChild("Progress") end; if T then else T = S:FindFirstChild("Pointer") end; local U = T; local V = U;
if V then V = U:IsA("GuiObject") end; if not V then return end; U.Position = UDim2.new(0.5, 0., U.Position.Y.Scale, 0.); if ReplicatedStorage:FindFirstChild("Fishing") then ReplicatedStorage.Fishing:FireServer("1") else local W = (ReplicatedStorage:FindFirstChild("Events"));
if W then W = ReplicatedStorage.Events:FindFirstChild("Fishing") end; if W then ReplicatedStorage.Events.Fishing:FireServer("1") end end end) end) end elseif fishingBarLockConnection then fishingBarLockConnection:Disconnect(); fishingBarLockConnection = nil
end end; aW = 30. end elseif aW == 15135. then aW = if aS <= ba[60.] then 19 else 29 else aW = 9845; continue end elseif aW < 15137 then if aW == 15136 then aQ = (aQ + ba[36.]) % ba[73]; aW = 23 else aW = 15170; continue end elseif aW < 15138. then aW = 27.
else aW = 31 end elseif aW < 15142 then if aW < 15141. then if aW < 15140 then if aW == 15139 then aW = 2 else aW = 15152; continue end else aW = 16 end else aQ = (aQ + ba[60.]) % ba[73]; aW = 21. end elseif aW < 15143 then aW = 37 else aQ = (aQ + ba[60.]) % ba[73];
aW = 17 end elseif aW < 15150. then if aW < 15148 then if aW < 15147. then if aW < 15146 then if aW < 15145 then break else aQ = (aQ + ba[56]) % ba[73]; aW = 6. end else aT = nil; local bj = ba; aT = bj[90.] - bj[48.]; aT = bj[41] + bj[60.]; aT = bj[48.] - bj[22];
aT = bj[48.] - bj[22]; aT = bj[41] + bj[60.]; aW = 15. end elseif aW == 15147. then local bj = ba; aL = bj[61]; aK = bj[83]; aW = 39. else aW = 15168.; continue end elseif aW < 15149 then aW = 35 else aW = 8 end elseif aW < 15153. then if aW < 15152 then if aW < 15151 then
if aW == 15150. then local bj = ba; aK = bj[61]; aL = bj[83]; aW = 39. else aW = 15173; continue end elseif aW == 15151 then aS = (aQ * ba[60.] + ba[48.]) % ba[90.] + ba[60.]; aW = 11 else aW = 15149; continue end elseif aW == 15152 then aW = 36. else aW = 15154;
continue end elseif aW < 15154 then if aW == 15153. then local bj = ba; aM = bj[2]; aJ = bj[17]; aW = 34 else aW = 15136; continue end elseif aW == 15154 then aW = 36. else aW = 15162.; continue end elseif aW < 15165. then if aW < 15160 then if aW < 15158 then
if aW < 15157 then if aW < 15156. then if aW == 15155 then local bk = bit32.rrotate(bit32.bxor(bit32.lrotate(aQ, ba[16]), string.byte(tostring(aP))), ba[16]); aW = if bit32.bxor(bit32.bxor(bit32.bxor(bit32.bxor(bit32.band(bk, ba[63.]), ba[8]), (bit32.bxor(bit32.band(bk, ba[29]), ba[45.]))), ba[8]), ba[45.]) ~= bk then 7 else 41
else aW = 15154; continue end else aW = 13 end else aW = if aS <= ba[48.] then 10 else 9. end elseif aW < 15159. then if aW == 15158 then aW = 38 else aW = 15144.; continue end else aW = if (aQ * ba[3.] + ba[56]) % ba[73] == ba[56] then 33. else 26 end elseif aW < 15163 then
if aW < 15162. then if aW < 15161 then local bj = ba; aT = (vector.create((aQ * bj[36.] + bj[56]) % bj[21.] + bj[60.], (aQ * bj[22] + bj[77]) % bj[4] + bj[60.], (aQ * bj[90.] + bj[56]) % bj[33.] + bj[60.])); local bl = vector.floor(aT) + vector.ceil(aT * bj[87.]);
aW = if vector.dot(bl, bl) == bj[41] + bj[48.] then 28 else 25 elseif aW == 15161 then local bj = ba; aS = (vector.create((aQ * bj[48.] + bj[48.]) % bj[21.] + bj[60.], (aQ * bj[22] + bj[48.]) % bj[4] + bj[60.], (aQ * bj[21.] + bj[73]) % bj[33.] + bj[60.]));
aT = (vector.create((aQ * bj[90.] + bj[22]) % bj[21.] + bj[60.], (aQ * bj[36.] + bj[56]) % bj[4] + bj[60.], (aQ * bj[18.] + bj[33.]) % bj[33.] + bj[60.])); aU = (vector.create((aQ * bj[36.] + bj[47]) % bj[21.] + bj[60.], (aQ * bj[47] + bj[7]) % bj[4] + bj[60.], (aQ * bj[3.] + bj[3.]) % bj[33.] + bj[60.]));
aV = (vector.create((aQ * bj[90.] + bj[36.]) % bj[36.] + bj[60.], (aQ * bj[36.] + bj[36.]) % bj[77] + bj[60.], (aQ * bj[60.] + bj[90.]) % bj[56] + bj[60.])); aW = if vector.dot(vector.cross(aS, (vector.cross(aT, aU))), aV) == vector.dot(aT * vector.dot(aS, aU) - aU * vector.dot(aS, aT), aV) then 12. else 5
else aW = 15172; continue end else local bj = ba; aT = (vector.create((aQ * bj[18.] + bj[47]) % bj[21.] + bj[60.], (aQ * bj[18.] + bj[47]) % bj[4] + bj[60.], (aQ * bj[56] + bj[33.]) % bj[33.] + bj[60.])); aU = (vector.create((aQ * bj[77] + bj[36.]) % bj[21.] + bj[60.], (aQ * bj[21.] + bj[22]) % bj[4] + bj[60.], (aQ * bj[48.] + bj[21.]) % bj[33.] + bj[60.]));
aV = (vector.create((aQ * bj[36.] + bj[90.]) % bj[36.] + bj[60.], (aQ * bj[36.] + bj[90.]) % bj[77] + bj[60.], (aQ * bj[36.] + bj[22]) % bj[56] + bj[60.])); aW = if math.abs((vector.angle(aT, aU, aV))) - math.abs((vector.angle(aU, aT, aV))) == bj[41] then 1 else 22
end elseif aW < 15164 then aI = ba[31]; aW = 32 else local bj = ba; aZ = if aS <= bj[22] then bj[60.] else bj[41]; aX = bj[71] * aZ + bj[59] * (bj[60.] - aZ); aY = bj[101] * aZ + bj[88] * (bj[60.] - aZ); aW = if (aX * bj[1] + aY * bj[92] + aX * aY) % bj[67] == bj[55] then 4 else 3.
end elseif aW < 15170 then if aW < 15168. then if aW < 15167 then if aW < 15166 then aW = 20 else aS = nil; local bj = ba; aS = bj[90.] - bj[48.]; aS = bj[36.] - bj[90.]; aS = bj[41] + bj[60.]; aS = bj[36.] - bj[90.]; aS = bj[41] + bj[60.]; aW = 14 end elseif aW == 15167 then
aW = if true then 24. else 37 else aW = 11485; continue end elseif aW < 15169 then aP = ba[14]; aO = function(F) config.AutoBossRhythm = F; if runThread then task.cancel(runThread); runThread = nil end; if F then runThread = task.spawn(aN); Library:Notify("\u{2705}BOSS\u{81EA}\u{52A8}\u{70B9}\u{51FB}\u{5F00}\u{542F}", 2)
else Library:Notify("\u{274C}BOSS\u{81EA}\u{52A8}\u{70B9}\u{51FB}\u{5173}\u{95ED}", 2) end end; aN = function(I) if I then if not autoCastThread then autoCastThread = task.spawn(function() while true do if getgenv().NWKZ_AutoCast then pcall(function() local J = (ReplicatedStorage:FindFirstChild("Events"));
if J then J = ReplicatedStorage.Events:FindFirstChild("Fishing") end; if J then ReplicatedStorage.Events.Fishing:FireServer() elseif ReplicatedStorage:FindFirstChild("Fishing") then ReplicatedStorage.Fishing:FireServer() end end); task.wait(0.3) else break
end end; autoCastThread = nil end) end elseif autoCastThread then task.cancel(autoCastThread); autoCastThread = nil end end; aR = function(L) if L then if not fishingBarLockConnection then fishingBarLockConnection = RunService.RenderStepped:Connect(function()
pcall(function() local M = localPlayer:FindFirstChild("PlayerGui"); if not M then return end; local O = (M:FindFirstChild("MainGui")); if O then O = M.MainGui:FindFirstChild("Fishing") end; local N = O; if N then else N = M:FindFirstChild("Fishing") end; if N then else
N = M:FindFirstChild("FishingUI") end; local P = N; local Q = P; if Q then Q = P.Visible end; if not Q then return end; local R = (P:FindFirstChild("FishingBar")); if R then else R = P:FindFirstChild("BarFrame") end; if R then else R = P:FindFirstChild("Bar")
end; local S = R; if not S then return end; local T = (S:FindFirstChild("Bar")); if T then else T = S:FindFirstChild("Slider") end; if T then else T = S:FindFirstChild("Progress") end; if T then else T = S:FindFirstChild("Pointer") end; local U = T; local V = U;
if V then V = U:IsA("GuiObject") end; if not V then return end; U.Position = UDim2.new(0.5, 0., U.Position.Y.Scale, 0.); if ReplicatedStorage:FindFirstChild("Fishing") then ReplicatedStorage.Fishing:FireServer("1") else local W = (ReplicatedStorage:FindFirstChild("Events"));
if W then W = ReplicatedStorage.Events:FindFirstChild("Fishing") end; if W then ReplicatedStorage.Events.Fishing:FireServer("1") end end end) end) end elseif fishingBarLockConnection then fishingBarLockConnection:Disconnect(); fishingBarLockConnection = nil
end end; aW = 30. else aW = 38 end elseif aW < 15173 then if aW < 15172 then if aW < 15171. then if aW == 15170 then aO = ba[31]; aW = 32 else aW = 9845; continue end else aW = 40 end else aT = nil; local bj = ba; aT = bj[90.] - bj[22]; aT = bj[60.] + bj[60.];
aW = 18. end elseif aW < 15174. then if aW == 15173 then aW = 35 else aW = 15145; continue end elseif aW < 15175 then local bj = ba; aJ = bj[2]; aM = bj[17]; aW = 34 else local bj = ba; bj[78.], bj[49], bj[65], bj[101], bj[8], bj[33.], bj[56], bj[72.], bj[76] = bj[78.], bj[8], bj[76], bj[56], bj[101], bj[49], bj[65], bj[72.], bj[33.];
bj[94], bj[66.], bj[7], bj[40], bj[64], bj[38], bj[52], bj[85], bj[88], bj[93.], bj[58], bj[68], bj[14], bj[49], bj[86] = bj[94], bj[58], bj[66.], bj[86], bj[7], bj[38], bj[88], bj[93.], bj[68], bj[40], bj[64], bj[52], bj[14], bj[85], bj[49]; bj[23], bj[56], bj[82], bj[45.], bj[85], bj[49] = bj[82], bj[85], bj[23], bj[45.], bj[56], bj[49];
bj[13], bj[83], bj[73], bj[5], bj[74], bj[17], bj[54.], bj[58], bj[22], bj[39.], bj[89], bj[84.], bj[82], bj[30.] = bj[82], bj[54.], bj[39.], bj[89], bj[73], bj[22], bj[13], bj[84.], bj[30.], bj[5], bj[83], bj[17], bj[74], bj[58]; bj[87.], bj[39.], bj[92], bj[100], bj[17], bj[101], bj[7], bj[89], bj[95], bj[86], bj[34], bj[56], bj[32], bj[37], bj[69.], bj[65], bj[44], bj[46], bj[82] = bj[37], bj[101], bj[56], bj[69.], bj[65], bj[92], bj[39.], bj[89], bj[17], bj[95], bj[100], bj[34], bj[82], bj[86], bj[32], bj[46], bj[7], bj[44], bj[87.];
bj[87.], bj[99.], bj[77], bj[1], bj[69.], bj[84.] = bj[84.], bj[99.], bj[69.], bj[1], bj[77], bj[87.]; aI, aJ, aM, aK, aL, aN, aR, aO, aP, aQ = nil, nil, nil, nil, nil, nil, nil, nil, nil, nil; aQ = bj[41]; aW = 8 end end end
--[[==== 待混淆片段结束 ====]]

-- 把混淆后的代码全部写在上面的 [[ ]] 内部
]]

-- 动态加载混淆后的业务函数逻辑
loadstring(obfuscatedLogic)()

-- 事件绑定（明文保留）
local BossPhase2Setup = ReplicatedStorage:WaitForChild("Events"):WaitForChild("BossPhase2Setup")
BossPhase2Setup.OnClientEvent:Connect(function(data)
    config.CenterTolerance = StageConfig.Phase2.CenterTolerance
    config.PulseInterval = StageConfig.Phase2.PulseInterval
    print("[事件触发] ⚠️进入BOSS阶段2 | BarSpeed:",data.BarSpeed," HitboxW:",data.HitboxW)
    Library:Notify("检测到BOSS二阶段，切换中心对齐参数",2)
end)

local npcData = {
    Taoist = nil,
    Maoshan = nil,
    Enzo = nil
}

local ChatEvent = ReplicatedStorage:WaitForChild("Events"):WaitForChild("NotifyRobloxChat")
ChatEvent.OnClientEvent:Connect(function(msg)
    if msg == "Taoist has just arrived!" then
        local target = workspace:FindFirstChild("NPC") and workspace.NPC:FindFirstChild("Function") and workspace.NPC.Function:FindFirstChild("Taoist")
        if target and target:FindFirstChild("HumanoidRootPart") then
            npcData.Taoist = target.HumanoidRootPart.CFrame
            Library:Notify("✅Taoist【道人🔸】出现了",1.5)
        end
    elseif msg == "Maoshan has just arrived!" then
        local target = workspace:FindFirstChild("NPC") and workspace.NPC:FindFirstChild("Function") and workspace.NPC.Function:FindFirstChild("Maoshan")
        if target and target:FindFirstChild("HumanoidRootPart") then
            npcData.Maoshan = target.HumanoidRootPart.CFrame
            Library:Notify("✅Maoshan【茅山🔹】出现了",1.5)
        end
    elseif msg == "All secret bosses have been despawned!" then
        npcData.Taoist = nil
        npcData.Maoshan = nil
        npcData.Enzo = nil
        Library:Notify("⚠️全部天气⛅已消失",1.5)
    end
end)

task.spawn(function()
    while task.wait(0.6) do
        local npcFolder = workspace:FindFirstChild("NPC")
        if npcFolder then
            local funcFolder = npcFolder:FindFirstChild("Function")
            if funcFolder then
                local taoistObj = funcFolder:FindFirstChild("Taoist")
                if taoistObj and taoistObj:FindFirstChild("HumanoidRootPart") then
                    npcData.Taoist = taoistObj.HumanoidRootPart.CFrame
                else
                    npcData.Taoist = nil
                end
                local maoshanObj = funcFolder:FindFirstChild("Maoshan")
                if maoshanObj and maoshanObj:FindFirstChild("HumanoidRootPart") then
                    npcData.Maoshan = maoshanObj.HumanoidRootPart.CFrame
                else
                    npcData.Maoshan = nil
                end
            end

            local bossFolder = npcFolder:FindFirstChild("Boss")
            if bossFolder then
                local enzoObj = bossFolder:FindFirstChild("Enzo")
                if enzoObj and enzoObj:FindFirstChild("HumanoidRootPart") then
                    npcData.Enzo = enzoObj.HumanoidRootPart.CFrame
                else
                    npcData.Enzo = nil
                end
            else
                npcData.Enzo = nil
            end
        else
            npcData.Taoist = nil
            npcData.Maoshan = nil
            npcData.Enzo = nil
        end
    end
end)

local MapList = {
    {Name = "🏝️初始岛", CFrame = CFrame.new(-200.69,6.76,35.91,-0.00,-0.00,-1.00,-0.00,1.00,-0.00,1.00,-0.00,-0.00)},
    {Name = "🎍竹子岛", CFrame = CFrame.new(-1223.00,6.76,-24.10,1.00,0.00,-0.00,-0.00,1.00,-0.00,0.00,0.00,1.00)},
    {Name = "🥚核弹岛", CFrame = CFrame.new(65.50,6.76,1181.30,1.00,0.00,-0.00,-0.00,1.00,-0.00,0.00,0.00,1.00)},
    {Name = "🌐主权岛", CFrame = CFrame.new(-1276.40,6.76,1239.70,1.00,-0.00,0.00,0.00,1.00,-0.00,-0.00,0.00,1.00)},
    {Name = "🐟鲈鱼岛", CFrame = CFrame.new(-61.99,9.28,-1321.42,1.00,0.00,0.00,-0.00,1.00,0.00,-0.00,-0.00,1.00)},
    {Name = "🏔️冰霜岛", CFrame = CFrame.new(-1365.99,9.28,-1495.42,1.00,0.00,0.00,-0.00,1.00,0.00,-0.00,-0.00,1.00)},
    {Name = "🏝️椰子岛", CFrame = CFrame.new(1493.61,6.76,-1430.62,1.00,0.00,0.00,0.00,1.00,-0.00,-0.00,0.00,1.00)},
    {Name = "🔮琥珀岛", CFrame = CFrame.new(1259.41,6.76,1401.48,1.00,0.00,-0.00,-0.00,1.00,-0.00,0.00,0.00,1.00)},
    {Name = "🌋战场岛", CFrame = CFrame.new(1342.56,9.28,229.71,1.00,-0.00,0.00,0.00,1.00,-0.00,-0.00,0.00,1.00)},
    {Name = "🌊迷雾岛", CFrame = CFrame.new(2660.22,6.78,-86.72,1.00,-0.00,0.00,0.00,1.00,-0.00,-0.00,0.00,1.00)}
}

local Window = Library:CreateWindow({
    Title = "重型钓鱼HUB",
    Footer = "原作者是个人",
    NotifySide = "Right"
})
local Tabs = {
    Main = Window:AddTab("Boss钓鱼","fish"),
    TeleportTab = Window:AddTab("🏝️地图传送","map"),
    Settings = Window:AddTab("设置","settings")
}

local Group = Tabs.Main:AddLeftGroupbox("BOSS小游戏自动操作")
Group:AddToggle("RhythmToggle",{
    Text = "开启BOSS自动点击",
    Default = false,
    Callback = function(val) ToggleRhythmBot(val) end
})
Group:AddSlider("CenterTolSlider",{
    Text = "中心对齐容差",
    Default = 0.042,
    Min = 0.015,
    Max = 0.12,
    Rounding = 3,
    Callback = function(v) config.CenterTolerance = v end
})
Group:AddSlider("PulseSlider",{
    Text = "点击脉冲间隔(秒)",
    Default = 0.045,
    Min = 0.02,
    Max = 0.12,
    Rounding = 3,
    Suffix = " s",
    Callback = function(v) config.PulseInterval = v end
})

Group:AddDivider()
Group:AddButton({
    Text = "🐛购买饵料",
    Callback = function()
        local VisibleUI = ReplicatedStorage:WaitForChild("Events"):WaitForChild("VisibleUI")
        pcall(function() VisibleUI.OnClientEvent:Fire("BaitShop") end)
        Library:Notify("打开购买饵料界面",1.2)
    end
})
Group:AddButton({
    Text = "🍟制作饵料",
    Callback = function()
        local VisibleUI = ReplicatedStorage:WaitForChild("Events"):WaitForChild("VisibleUI")
        pcall(function() VisibleUI.OnClientEvent:Fire("CraftBait") end)
        Library:Notify("打开制作饵料界面",1.2)
    end
})
Group:AddButton({
    Text = "🔶远程抽词条",
    Callback = function()
        local VisibleUI = ReplicatedStorage:WaitForChild("Events"):WaitForChild("VisibleUI")
        pcall(function() VisibleUI.OnClientEvent:Fire("Trait") end)
        Library:Notify("打开抽词条界面",1.2)
    end
})
Group:AddButton({
    Text = "🐟自动卖鱼",
    Callback = function()
        local SellFish = ReplicatedStorage:WaitForChild("Events"):WaitForChild("SellFish")
        pcall(function() SellFish:FireServer("Colossal Tigerfish | 4180092.92 | Favorite") end)
        Library:Notify("执行自动卖鱼",1.2)
    end
})

Group:AddDivider()
Group:AddButton({
    Text = "传送到 Taoist（道士🔸）",
    Callback = function()
        local char = localPlayer.Character
        if not char or not char:FindFirstChild("HumanoidRootPart") then
            Library:Notify("角色未加载",1.5)
            return
        end
        if not npcData.Taoist then
            Library:Notify("Taoist 道士🔸尚未刷新",2)
            return
        end
        char.HumanoidRootPart.CFrame = npcData.Taoist + Vector3.new(0,3.5,0)
        Library:Notify("成功传送至 Taoist 道人",1.5)
    end
})
Group:AddButton({
    Text = "传送到 Maoshan（茅山🔹）",
    Callback = function()
        local char = localPlayer.Character
        if not char or not char:FindFirstChild("HumanoidRootPart") then
            Library:Notify("角色未加载",1.5)
            return
        end
        if not npcData.Maoshan then
            Library:Notify("Maoshan 茅山尚未刷新",2)
            return
        end
        char.HumanoidRootPart.CFrame = npcData.Maoshan + Vector3.new(0,3.5,0)
        Library:Notify("成功传送至 Maoshan 茅山",1.5)
    end
})
Group:AddButton({
    Text = "传送到 Enzo♦️",
    Callback = function()
        local char = localPlayer.Character
        if not char or not char:FindFirstChild("HumanoidRootPart") then
            Library:Notify("角色未加载",1.5)
            return
        end
        if not npcData.Enzo then
            Library:Notify("Enzo Boss尚未刷新",2)
            return
        end
        char.HumanoidRootPart.CFrame = npcData.Enzo + Vector3.new(0,3.5,0)
        Library:Notify("成功传送至 Enzo",1.5)
    end
})

local FishingRightGroup = Tabs.Main:AddRightGroupbox("普通钓鱼功能")
FishingRightGroup:AddToggle("AutoCastToggle",{
    Text = "自动抛竿",
    Default = false,
    Callback = function(val)
        getgenv().NWKZ_AutoCast = val
        ToggleAutoCast(val)
    end
})
FishingRightGroup:AddToggle("AnchorToggle",{
    Text = "自动钓鱼",
    Default = false,
    Callback = function(val)
        getgenv().NWKZ_Anchor = val
        ToggleFishingBarLock(val)
    end
})

local TeleportGroup = Tabs.TeleportTab:AddLeftGroupbox("地图传送功能")
for _,mapData in ipairs(MapList) do
    TeleportGroup:AddButton({
        Text = mapData.Name,
        Callback = function()
            local char = localPlayer.Character
            if char and char:FindFirstChild("HumanoidRootPart") then
                char.HumanoidRootPart.CFrame = mapData.CFrame
                Library:Notify("传送至："..mapData.Name,1.5)
            end
        end
    })
end

local SetGroup = Tabs.Settings:AddLeftGroupbox("脚本设置")
SetGroup:AddButton("卸载脚本",function()
    config.AutoBossRhythm = false
    if runThread then task.cancel(runThread) end

    if autoCastThread then
        task.cancel(autoCastThread)
        autoCastThread = nil
    end
    if fishingBarLockConnection then
        fishingBarLockConnection:Disconnect()
        fishingBarLockConnection = nil
    end
    getgenv().NWKZ_AutoCast = false
    getgenv().NWKZ_Anchor = false

    Library:Unload()
end)
SetGroup:AddLabel("菜单快捷键"):AddKeyPicker('MenuKeybind', { Default = 'RightShift', NoUI = true})
Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:BuildConfigSection(Tabs.Settings)
ThemeManager:ApplyToTab(Tabs.Settings)
